#!/usr/bin/env ruby

require 'active_support'	#	for alias_method_chain

#	how do I colorize with the whole red green thing

class Autotest

	def run_tests_with_correct_unit_diff
		#http://syntatic.wordpress.com/2009/08/13/jruby-1-3-0-with-autotest/
		self.unit_diff = if RUBY_PLATFORM == 'java'
			"unit_diff"
		else
			"unit_diff -u"
		end
		run_tests_without_correct_unit_diff
	end
	alias_method_chain :run_tests, :correct_unit_diff

	def rerun_all_tests_with_flag
		#
		#		use some sort of command line option to stop this
		#		surprised this doesn't exist
		#

		#	perhaps set this flag in a file so that can be modified
		#	without restarting autotest.

		unless ENV['AUTOTEST_RERUN_ALL'] == 'false'
			rerun_all_tests_without_flag
		end
	end
	alias_method_chain :rerun_all_tests, :flag

end
