#	
#	GEM_PATH=$GEM_PATH:$HOME/.gem
#	export GEM_PATH
#	
#	GEM_HOME=~/.gem
#	export GEM_HOME
#	
#	PATH=$PATH:$HOME/bin
#	export PATH
#	
#	EDITOR=vi
#	export EDITOR
#	

#	Default
#PS1=\h:\W \u\$
PS1='\[\e[1;1m\][\u@\h \w]\$\[\e[0m\] '

#	sudo port install bedtools boost bowtie cmake coreutils curl ds9 gnupg gnuplot gnutar gnutls gzip lftp mariadb parallel pstree py27-pip R samtools unzip util-linux wget wput bash vim git gawk mariadb
#
#	sudo port select pip pip27
#	sudo port select mysql mariadb

#	cd ~; ln -s Library/Python/2.7/ .python
#	pip install --user awscli
#	pip install --user deepTools

#	Install kent utils
#	Install bowtie2
#	Install trinity

#PATH=${HOME}/local/bin:${HOME}/.trinity:${HOME}/RINS_BASE/bin:${PATH}:${HOME}/local/sbin:${HOME}/.python/bin:${HOME}/.kentutils/bin
export PATH=${HOME}/local/bin:${HOME}/.python/bin:${HOME}/.kentutils/bin:/opt/local/libexec/gnubin:/opt/local/bin:/opt/local/sbin:${PATH}

#	Use gnu utils be default ...
#	 /opt/local/libexec/gnubin/


alias port_update="sudo port -F ~/port_update.port"
#    selfupdate
#    upgrade outdated
#    uninstall inactive
#    clean --all installed

#	Put /opt/local/libexec/gnubin in PATH so these 3 aliases aren't needed.
#alias du=gdu
#alias awk=gawk
#alias readlink=greadlink

alias grep="grep -is"
alias ..="cd .."
alias cd..="cd .."
alias la="\ls -al --color=auto"
alias ll="\ls -lG --color=auto"
alias ln="ln -s"
alias more="less"
alias rm="rm -i"
alias h=history
alias c="for i in {1..50}; do echo; done"

#	
#	"Better" done in .inputrc
#set -o vi

#	same result
#xyz() {
#	echo $1
#}
function relink {
	rm $1
	ln -s $2 $1
}

export DAPPP="/opt/local/bin/dappp"
export DAPRUNS="/opt/local/bin/dapruns"
export INCDIR="/opt/local/include"
export LIBDIR="/opt/local/lib"

export GEM_HOME="${HOME}/.gem/ruby/2.2.0"
export PATH=${GEM_HOME}/bin:${PATH}

#	for whatever reason, qt4-mac doesn't install qmake in the standard bin
#export PATH=/opt/local/libexec/qt4/bin:${PATH}

