#	
#	GEM_PATH=$GEM_PATH:$HOME/.gem
#	export GEM_PATH
#	
#	GEM_HOME=~/.gem
#	export GEM_HOME
#	
#	PATH=$PATH:$HOME/bin
#	export PATH
#	
#	EDITOR=vi
#	export EDITOR
#	

#	Default
#PS1=\h:\W \u\$
PS1='\[\e[1;1m\][\u@\h \w]\$\[\e[0m\] '

#	sudo port install bedtools boost bowtie cmake coreutils curl ds9 gnupg gnuplot gnutar gnutls gzip lftp mariadb parallel pstree py27-pip R samtools unzip util-linux wget wput bash vim git gawk mariadb qt4-mac qt5 ruby20 ruby21 ruby22 ruby23
#
#	sudo port select pip pip27
#	sudo port select mysql mariadb
#	sudo /opt/local/share/mariadb/support-files/mysql.server start
#	sudo /opt/local/apache2/bin/apachectl start

#	postgresql

#	cd ~; ln -s Library/Python/2.7/ .python
#	pip install --user awscli
#	pip install --user deepTools
#	pip install --user --upgrade awscli deeptools

#	Install kent utils
#		git clone git://github.com/ENCODE-DCC/kentUtils.git
#		cd kentUtils
#		make
#		mkdir -p ~/.kentutils/
#		mv bin ~/.kentutils/
#
#	Install blat
#		http://hgwdev.cse.ucsc.edu/~kent/src/
#		https://users.soe.ucsc.edu/~kent/src/
#
#	Install bowtie2
#	Install trinity

#PATH=${HOME}/local/bin:${HOME}/.trinity:${HOME}/RINS_BASE/bin:${PATH}:${HOME}/local/sbin:${HOME}/.python/bin:${HOME}/.kentutils/bin
export PATH=${HOME}/local/bin:${HOME}/.python/bin:${HOME}/.kentutils/bin:/opt/local/libexec/gnubin:/opt/local/bin:/opt/local/sbin:${PATH}

#	Use gnu utils by default ...
#	 /opt/local/libexec/gnubin/


alias port_update="sudo port -F ~/port_update.port"
#    selfupdate
#    upgrade outdated
#    uninstall inactive
#    clean --all installed

#	Put /opt/local/libexec/gnubin in PATH so these 3 aliases aren't needed.
#alias du=gdu
#alias awk=gawk
#alias readlink=greadlink

alias gzip="gzip --best"
alias grep="grep -is"
alias ..="cd .."
alias cd..="cd .."
alias la="\ls -al --color=auto"
alias ll="\ls -lG --color=auto"
alias ln="ln -s"
alias more="less"
alias rm="rm -i"
alias h=history
alias c="for i in {1..50}; do echo; done"

#	
#	"Better" done in .inputrc
#set -o vi

#	same result
#xyz() {
#	echo $1
#}
function relink {
	rm $1
	ln -s $2 $1
}

#	I've only ever had this successfully work with kentUtils for "mysqlclient"!
#	The value of LIBRARY_PATH is a colon-separated list of directories, much like PATH. When configured as a native compiler, GCC tries the directories thus specified when searching for special linker files, if it can't find them using GCC_EXEC_PREFIX. Linking using GCC also uses these directories when searching for ordinary libraries for the -l option (but directories specified with -L come first).
export LIBRARY_PATH="/opt/local/lib/mariadb/mysql/"

export DAPPP="/opt/local/bin/dappp"
export DAPRUNS="/opt/local/bin/dapruns"
export INCDIR="/opt/local/include"
export LIBDIR="/opt/local/lib"

#export GEM_HOME="${HOME}/.gem/ruby/2.2.0"
export GEM_HOME="${HOME}/.gem/ruby/2.3"
export GEM_PATH=$GEM_HOME
export PATH=${GEM_HOME}/bin:${PATH}

#	for whatever reason, qt4-mac doesn't install qmake in the standard bin
#export PATH=/opt/local/libexec/qt4/bin:${PATH}
#	for whatever reason, qt5 doesn't install qmake in the standard bin
#export PATH=/opt/local/libexec/qt5/bin:${PATH}

