# A sample Gemfile
source "http://rubygems.org"
source "http://gems.rubyforge.org"
source "http://gemcutter.org"
source "http://gems.github.com"


#	rubygems > 1.6.2 is EVIL!  If you update, you deal with it.
#		generates all kinds of new errors and deprecation warnings
#		somehow loads older versions of gems, then bitches when you try to load the newest.
#		(may be fixable with "gem pristine --all --no-extensions", but haven't tried)
#	rake 0.9.0 caused some errors.  can't remember
#	arel > 2.0.2 caused some errors.
#	some gem versions require rails 3, so have to use older versions
#		authlogic, will_paginate


#
#	NO SPACES BETWEEN OPERATOR AND VERSION NUMBER!
#
gem "rake", '=0.8.7'
gem "rails", "~>2"
#gem "test-unit"
gem "mongrel"
gem "active_shipping"
gem "RedCloth", '<4.2.8'
gem "arel", "=2.0.2"
gem "authlogic", "~>2"
gem "autotest-rails"
gem "aws-s3"
gem "aws-sdb"
#	jakewendt@dev : ccls 589> irb
#	>> gem 'chronic', '0.6.0'
#	=> true
#	>> require 'chronic'
#	=> true
#	>> Chronic::VERSION
#	=> "0.6.0"
#	>> Chronic.parse('Jan 1 2000')
#	=> nil
#	>> quit
#	jakewendt@dev : ccls 590> irb
#	>> gem 'chronic', '0.5.0'
#	=> true
#	>> require 'chronic'
#	=> true
#	>> Chronic::VERSION
#	=> "0.5.0"
#	>> Chronic.parse('Jan 1 2000')
#	=> Sat Jan 01 12:00:00 -0800 2000
gem "chronic"	#, '=0.5.0'	#	0.6.0 doesn't parse correctly which is odd #	fixed by 0.6.2
gem "gravatar"
gem "haml"
gem "hpricot"
gem "i18n"
gem "jeweler"
gem "jrails"
gem "paperclip"
#	causes rails 2.3.2 and associated to be installed???
#gem "rack"	
# (1.3.0, 1.2.2, 1.1.2, 1.1.0, 1.0.1)
gem "rcov"
gem "rdoc"
gem "ryanb-acts-as-list"
gem "ssl_requirement"
gem "thoughtbot-factory_girl"
gem "will_paginate", "~>2"

gem "ccls-calnet_authenticated"
gem "ccls-ccls_engine"
#gem "ccls-surveyor"
gem "jakewendt-html_test"
gem "jakewendt-rails_extension"
gem "jakewendt-rdoc_rails"
gem "jakewendt-ruby_extension"
gem "jakewendt-simply_authorized"
gem "jakewendt-simply_documents"
gem "jakewendt-simply_helpful"
gem "jakewendt-simply_pages"
gem "jakewendt-simply_photos"
gem "jakewendt-simply_sessions"
#gem "jakewendt-simply_testable"
gem "jakewendt-simply_trackable"
gem "jakewendt-use_db"

#/Library/Ruby/Gems/1.8/gems/ZenTest-4.6.0/lib/autotest.rb:226:in `autodiscover': undefined method `any?' for Gem::Specification:Class (NoMethodError)
#	from /Library/Ruby/Gems/1.8/gems/ZenTest-4.6.0/lib/autotest.rb:150:in `runner'
#	from /Library/Ruby/Gems/1.8/gems/ZenTest-4.6.0/bin/autotest:6
#	from /usr/bin/autotest:19:in `load'
#	from /usr/bin/autotest:19
gem 'ZenTest', '~>4.5.0'
#gem 'ZenTest', '!=4.6.0'
#gem 'ZenTest', '!=4.6.1'	#	requires
#	rubygems > 1.6.2 (mostly the 1.8 family) just bitches and causes all kinds of errors
#	somehow older versions of gems get activated, then when something tries to use the latest
#	I get stuff like ...
#/Library/Ruby/Site/1.8/rubygems/specification.rb:1603:in `raise_if_conflicts': can't activate jakewendt-simply_helpful-2.2.14, already activated jakewendt-simply_helpful-2.2.12 (Gem::LoadError)
#	why was 2.2.12 activated?  I never explicitly activated any version of simply_helpful
#	I tried "gem cleanup" but that failed with ... for every gem
# ERROR:  While executing gem ... (ArgumentError)
#    wrong number of arguments (3 for 2)
#
#	also get lots of ...
#Gem.source_index called from /usr/lib/ruby/user-gems/1.8/gems/rails-2.3.12/lib/rails/gem_dependency.rb:78.
#NOTE: Gem::SourceIndex#each is deprecated with no replacement. It will be removed on or after 2011-11-01.
#Gem::SourceIndex#each called from /usr/lib/ruby/user-gems/1.8/gems/rails-2.3.12/lib/rails/vendor_gem_source_index.rb:123.
#NOTE: Gem::SourceIndex#each is deprecated with no replacement. It will be removed on or after 2011-11-01.
#Gem::SourceIndex#each called from /usr/lib/ruby/user-gems/1.8/gems/rails-2.3.12/lib/rails/vendor_gem_source_index.rb:124.
#	I hope that there is a rails-2.3.13 in the works to shut this up since I can't upgrade to 3



if RUBY_PLATFORM =~ /java/
	gem "warbler"
	gem "jruby-jars"
	gem "jruby-openssl"
	gem "jruby-rack"
	gem "jdbc-mysql"
	gem "jdbc-sqlite3"
	gem "activerecord-jdbcsqlite3-adapter"
	gem "activerecord-jdbcmysql-adapter"
else
	#	problems in jruby
	gem "mysql"
	gem "rmagick"
	gem "sqlite3", '!=1.3.4'
end

gem "fastercsv"
gem "sunspot_rails"
gem "sunspot"
gem "packet"	#	don't remember why

