# A sample Gemfile
source "http://rubygems.org"
source "http://gems.rubyforge.org"
source "http://gemcutter.org"
source "http://gems.github.com"


#
#	NO SPACES BETWEEN OPERATOR AND VERSION NUMBER!
#
gem "rake", '=0.8.7'
gem "rails", "~>2"
gem "mongrel"
gem "active_shipping"
gem "RedCloth"
gem "arel", "=2.0.2"
gem "authlogic", "~>2"
gem "autotest-rails"
gem "aws-s3"
gem "aws-sdb"
#	jakewendt@dev : ccls 589> irb
#	>> gem 'chronic', '0.6.0'
#	=> true
#	>> require 'chronic'
#	=> true
#	>> Chronic::VERSION
#	=> "0.6.0"
#	>> Chronic.parse('Jan 1 2000')
#	=> nil
#	>> quit
#	jakewendt@dev : ccls 590> irb
#	>> gem 'chronic', '0.5.0'
#	=> true
#	>> require 'chronic'
#	=> true
#	>> Chronic::VERSION
#	=> "0.5.0"
#	>> Chronic.parse('Jan 1 2000')
#	=> Sat Jan 01 12:00:00 -0800 2000
gem "chronic", '=0.5.0'	#	0.6.0 doesn't parse correctly which is odd
gem "gravatar"
gem "haml"
gem "hpricot"
gem "i18n"
gem "jeweler"
gem "jrails"
gem "paperclip"
#	causes rails 2.3.2 and associated to be installed???
#gem "rack"	
# (1.3.0, 1.2.2, 1.1.2, 1.1.0, 1.0.1)
gem "rcov"
gem "rdoc"
gem "ryanb-acts-as-list"
gem "ssl_requirement"
gem "thoughtbot-factory_girl"
gem "will_paginate"

gem "ccls-calnet_authenticated"
gem "ccls-ccls_engine"
gem "ccls-surveyor"
gem "jakewendt-html_test"
gem "jakewendt-rails_extension"
gem "jakewendt-rdoc_rails"
gem "jakewendt-ruby_extension"
gem "jakewendt-simply_authorized"
gem "jakewendt-simply_documents"
gem "jakewendt-simply_helpful"
gem "jakewendt-simply_pages"
gem "jakewendt-simply_photos"
gem "jakewendt-simply_sessions"
#gem "jakewendt-simply_testable"
gem "jakewendt-simply_trackable"
gem "jakewendt-use_db"

if RUBY_PLATFORM =~ /java/
	gem "warbler"
	gem "jruby-jars"
	gem "jruby-openssl"
	gem "jruby-rack"
	gem "jdbc-mysql"
	gem "jdbc-sqlite3"
else
	#	problems in jruby
	gem "mysql"
	gem "rmagick"
	gem "sqlite3"
end
