#!/usr/bin/perl -w

use strict;

my $execname;
my $filename = "";
my $FUNCNAME = "componentcheck";
my $FUNCVERSION = "1.0";

# exit unless ( $#ARGV >= 0 );

while ($_ = $ARGV[0], /^-.*/) {
	if ($_ eq "-h"		||
		$_ eq "--h"		||
		$_ eq "--help") {
		print 
		"\n\n"
		."Usage:  $FUNCNAME  [options] file(s)\n"
		."\n"
		."  -v, --v, --version -> version number\n"
		."  -h, --h, --help    -> this help message\n"
		."  --value, --values  -> compares values also\n"
		."     by default, parcheck only compares parameter names\n"
		."\n\n"
		; # closing semi-colon
		exit 0;
	}

	elsif ($_ eq "-v"		||
		$_ eq "--v"			||
		$_ eq "--version") {
		print "Log_1  : Version : $FUNCNAME $FUNCVERSION\n";
		exit 0;
	}

	else {  # all other cases
		print "ERROR: unrecognized option +$ARGV[0]+.  Aborting...\n";
		print "\n";
		exit 1;
	}
	shift @ARGV;
}     # while options left on the command line


while ( $ARGV[0] ) {
	$filename = $ARGV[0];
	open CURFILE, $filename;
	while (<CURFILE>) {
	next if ( /^\s*#/ );
		next if ( /^\s*$/ );
		if ( /\"program_name\"/ ) {
			$execname = $_;
			ExecName ( );
		}
	}
	close CURFILE;
	shift @ARGV;
}     # while options left on the command line

exit;


#########################################################

sub ExecName {

	$execname =~ s/^(\s*\"program_name\"\s*\=\>\s*\")//;
	$execname =~ s/(\"\,\s*)$//;

	return 1  if ( $execname =~ /NONE/ );
	return 2  if ( $execname =~ /ERROR/ );
	return 3  if ( $execname =~ /ISDCPipeline/ );
	return 4  if ( $execname =~ /touch/ );
	return 5  if ( $execname =~ /COPY/ );
	return 6  if ( $execname =~ /CHECK/ );
	return 7  if ( $execname =~ /osf_create/ );
	return 8  if ( $execname =~ /osf_update/ );
	return 9  if ( $execname =~ /^tar / );
	return 10 if ( $execname =~ /^mv / );
	return 11 if ( $execname =~ /^cp / );

	print $execname."\n";
	return 0;
}


__END__


