#!/bin/sh -x

Date=`date "+%Y%m%d%H%M%S"`

#BackupDir=/Volumes/Passport/Backups/MBP
BackupDir=/Volumes/Passport/Backups/MBP2

if [ ! -d $BackupDir ]
then
	echo "$BackupDir doesn't exist"
	exit
else
	echo "$BackupDir exists"
fi

#	-a = -rlptgoD
#	g - groups have become a problem so I'm ignorin em
#	t - times have become a problem so I'm ignorin em (doesn't seem to matter either way with extended attributes)
#	D - devices are pointless here so I'm ignorin em
#	r - recursive
#	l - links
#	p - permissions
#	o - owner
#	v - verbose
#	z - compression
#	c - checksum
#	--exclude="Documents" \
#	--exclude="Records.original" \
#	--exclude="Records" \
#	--exclude="EncryptedRecords" \
#	--exclude="Records.sparsebundle" \
#
#	contains copies of those in Movies.
#	may want to just have these if start doing more video
#	--exclude="Movies/iMovie Events.localized" \
#	--extended-attributes \

#/usr/bin/rsync -rltpvzX \
#rsync -rltpvzX \
#	Newer versions of rsync use -X instead of --extended-attributes which is much better
#
#	--exclude="Desktop/Dad/Desktop Computer/My Music" \
#
#	--exclude="Library/Preferences/Macromedia" \
#	--exclude="Library/Application Support/Adobe/Adobe Device Central CS3" \
#	--exclude="Library/Application Support/Garmin/Maps/*.gmap" \
#	--exclude="Library/Application Support/SyncServices" \
#	--exclude="Library/Caches" \
#	--exclude="Library/Google" \
#	--exclude="Library/Internet Plug-Ins" \
#	--exclude="Library/Logs" \
#	--exclude="Library/Saved Application State" \


rsync -avzX \
	--progress \
	--delete --backup --backup-dir rsync-backup-deleted-$Date \
	--exclude="AppleWorks User Data" \
	--exclude="Acrobat User Data" \
	--exclude="Android" \
	--exclude="Applications" \
	--exclude="AMI/sequers" \
	--exclude="AMI/hg19" \
	--exclude="Desktop/Incomplete" \
	--exclude="Desktop/Movies" \
	--exclude="Downloads" \
	--exclude="Eclipse" \
	--exclude="Incomplete" \
	--exclude="Library" \
	--exclude="Podcasts" \
	--exclude="Roxio Converted Items" \
	--exclude="Microsoft User Data" \
	--exclude="Xtorrent" \
	--exclude="Temp" \
	--exclude="hosting_rails/prod/sites/www/*.m4v" \
	--exclude="TV Shows" \
	--exclude="Viewed" \
	--exclude="herv" \
	--exclude="rsync-backup*" \
	--exclude="rsync-backup-deleted*" \
	--exclude="temp" \
	--exclude="tmp/cache" \
	--exclude="log/*.log" \
	--exclude="versions" \
	--exclude="ZZZ" \
	--exclude=.DS_Store \
	--exclude=.fseventsd \
	--exclude=.rvm \
	--exclude=.Trash \
	--exclude=.Trashes \
	--exclude=.TemporaryItems \
	--exclude=.Spotlight-V100 \
	--exclude=.android \
	--exclude=.bash_sessions \
	--exclude=.gem \
	--exclude=.gradle \
	--exclude=.dvdcss \
	--exclude=.jpi_cache \
	--exclude=.cisco \
	--exclude=.passenger \
	--exclude=.kentUtils \
	--exclude=.R \
	--exclude=solr/data/ \
	--exclude=tmp/cache/ \
	--exclude=\*NOT_BACKED_UP\* \
	/Users/jake/ $BackupDir/jake/



#	Need to use extended attributes to preserve iPhoto Library
#	unfortunately, it copies so much extra 
#	So many pointless FinderInfo and quarantine extended attributes on MY files
#
#Date=`date "+%y%m%d%H%M%S"`
#
#/usr/bin/rsync -rltpvz --progress \
#	--delete --backup --backup-dir rsync-backup-$Date \
#	--extended-attributes \
#	--exclude=rsync-backup\* \
#	--exclude=.DS_Store \
#	--exclude=temp \
#	--exclude=Viewed \
#	--exclude=Incomplete \
#	--exclude=Xtorrent \
#	--exclude=\*NOT_BACKED_UP\* \
#	--exclude="Downloads/*.mp4" \
#	--exclude="Downloads/**/*.mp4" \
#	--exclude="Downloads/**/*.wmv" \
#	/Users/Shared/ $BackupDir/Shared/
#
#	--exclude="github/ccls/sequencing/ncbi-blast-*/c++/*Debug*" \
