#!/bin/sh -x

Date=`date "+%y%m%d%H%M%S"`

BackupDir=/Volumes/LaCie328/Backups/MBP

if [ ! -d $BackupDir ]
then
	echo "$BackupDir doesn't exist"
	exit
#	mkdir -p $BackupDir
else
	echo "$BackupDir exists"
fi

#	-a = -rlptgoD
#	g - groups have become a problem so I'm ignorin em
#	t - times have become a problem so I'm ignorin em
#	D - devices are pointless here so I'm ignorin em
#	r - recursive
#	l - links
#	p - permissions
#	o - owner
#	v - verbose
#	z - compression
#	c - checksum
#/usr/bin/rsync -avz \
#	--delete \
#	--exclude=Library \
/usr/bin/rsync -rltpvz \
	--progress \
	--extended-attributes \
	--delete --backup --backup-dir rsync-backup-$Date \
	--exclude="AppleWorks User Data" \
	--exclude="Acrobat User Data" \
	--exclude="Android" \
	--exclude="Desktop/Incomplete" \
	--exclude="Desktop/**/vid*" \
	--exclude="Desktop/**/*.mp4" \
	--exclude="Desktop/**/*/*.mp4" \
	--exclude="Documents" \
	--exclude="Downloads/**/*.mp4" \
	--exclude="Eclipse" \
	--exclude="Library/Preferences/Macromedia" \
	--exclude="Library/Application Support/Garmin/Maps/*.gmap" \
	--exclude="Library/Application Support/SyncServices" \
	--exclude="Library/Caches" \
	--exclude="Library/Google" \
	--exclude="Library/Mail/Bundles (Disabled)/GPGMail.mailbundle" \
	--exclude="Library/Logs" \
	--exclude="Podcasts" \
	--exclude="Records.original" \
	--exclude="Records" \
	--exclude="EncryptedRecords" \
	--exclude="Roxio Converted Items" \
	--exclude="Microsoft User Data" \
	--exclude="Temp" \
	--exclude="TV Shows" \
	--exclude="rsync-backup*" \
	--exclude="log/*.log" \
	--exclude=.fseventsd \
	--exclude=.rvm \
	--exclude=.Trash \
	--exclude=.Trashes \
	--exclude=.TemporaryItems \
	--exclude=.Spotlight-V100 \
	--exclude=.dvdcss \
	--exclude=.jpi_cache \
	--exclude=\*NOT_BACKED_UP\* \
	/Users/jake/ $BackupDir/jake/

#/usr/bin/rsync -rltpvz \
#	--progress \
#	--extended-attributes \
#	--delete --backup --backup-dir rsync-backup-$Date \
#	--exclude=rsync-backup\* \
#	/Users/jake/Documents/ $BackupDir/jake/Documents/

#	added extended-attributes for iPhoto Library

Date=`date "+%y%m%d%H%M%S"`
/usr/bin/rsync -rltpvz --progress \
	--delete --backup --backup-dir rsync-backup-$Date \
	--extended-attributes \
	--exclude=rsync-backup\* \
	--exclude=temp \
	--exclude=Viewed \
	--exclude=Incomplete \
	--exclude=Xtorrent \
	--exclude=\*NOT_BACKED_UP\* \
	/Users/Shared/ $BackupDir/Shared/

#/usr/bin/rsync -rltpvz \
#	--progress \
#	--delete --backup --backup-dir rsync-backup-$Date \
#	--exclude=rsync-backup\* \
#	/Users/Shared/iTunes/ $BackupDir/Shared/iTunes/

#  /Users/jake/Music/iTunes/iTunes\ Music/Podcasts/

#/usr/bin/rsync -avz \
#/usr/bin/rsync -rltpovz \
#	--progress \
#	--delete \
#	/Users/jake/Library/Mozilla/ $MozillaDir/

#	/usr/bin/rsync -avz --progress /Users/Shared/TV/Unviewed/ /Volumes/LaCie328/Public/TV/All\ Unviewed/
#	/usr/bin/rsync -avz --progress /Users/jake/Desktop/TV/All\ Unviewed/ /Volumes/LaCie328/Public/TV/All\ Unviewed/

#	/usr/bin/rsync -avz --progress /Users/Shared/Xtorrent/ /Volumes/LaCie328/Public/TV/Xtorrent/

#	/usr/bin/rsync -avz --progress /Users/Shared/iTunes/ /Volumes/LaCie328/Public/iTunes/

#	/usr/bin/rsync -avz --progress --exclude="Incomplete" /Users/Shared/Xtorrent/ /Volumes/LaCie328/Public/TV/Xtorrent/

#	/usr/bin/rsync -rltpovz --progress /Users/jake/Desktop/KeepOut/ /Volumes/LaCie328/KeepOut/

#	/usr/bin/rsync -rltpovz --progress --delete /Users/jake/Desktop/KeepOut/ /Volumes/LaCie328/KeepOut/

#	/usr/bin/rsync -rltpovz --progress --delete /Users/jake/Music/ /Volumes/LaCie328/Backups/iMacG5/Music/

