#!/bin/sh -x

BackupDir=/Volumes/THUMB/MBP

if [ ! -d $BackupDir ]
then
	echo "$BackupDir doesn't exist"
	exit
#	mkdir -p $BackupDir
else
	echo "$BackupDir exists"
fi

#	-a = -rlptgoD
#	g - groups have become a problem so I'm ignorin em
#	t - times have become a problem so I'm ignorin em
#	D - devices are pointless here so I'm ignorin em
#	r - recursive
#	l - links
#	p - permissions
#	t - times
#	o - owner
#	v - verbose
#	z - compression
#rsync -avz \
#	--delete \
#	--extended-attributes \
#	--size-only \
#	--ignore-times \
#	--exclude=Library \

# /bin/rm -rf /Volumes/THUMB/MBP/Library/Mail/*/*/*/Attachments/
#	/bin/rm -rf /Volumes/THUMB/MBP/Library/Mail/*/*/Attachments/
#	/bin/rm -rf /Volumes/THUMB/MBP/hostingrails.svn/references/videos
#	--exclude="upillar.svn/motors" \
#	--exclude="upillar.svn/classifieds/trunk/tmp/markup/" \
#	--exclude="upillar.svn/classifieds/trunk/doc/mockups/final mockup psds"  \
#	--exclude="Library/Mail/*/*/*/Attachments" \
#	--exclude="Library/Mail/RSS/*/Attachments" \
#	--exclude="Documents" \

/usr/bin/rsync -avz \
	--progress \
	--delete \
	--delete-excluded \
	--extended-attributes \
	--exclude="Acrobat User Data" \
	--exclude="Admin Drop Box" \
	--exclude="Android" \
	--exclude="Applications" \
	--exclude="AppleWorks User Data" \
	--exclude="Desktop" \
	--exclude="Downloads" \
	--exclude="Eclipse" \
	--exclude="Library/Screen Savers" \
	--exclude="Library/Mail/**/Attachments" \
	--exclude="Library/PubSub" \
	--exclude="Library/Logs" \
	--exclude="Library/Caches" \
	--exclude="Library/Fonts" \
	--exclude="Library/Application Support/Adobe" \
	--exclude="Library/Application Support/Skype" \
	--exclude="Library/Application Support/Garmin" \
	--exclude="Library/Application Support/CrashReporter" \
	--exclude="Library/Application Support/SyncServices" \
	--exclude="Library/Application Support/Firefox" \
	--exclude="Library/Mail/Bundles (Disabled)" \
	--exclude="Library/Internet Plug-Ins" \
	--exclude="Library/Preferences/NeoOffice-*" \
	--exclude="Library/Preferences/Macromedia" \
	--exclude="Library/Preferences/EPSON" \
	--exclude="Library/Preferences/Microsoft" \
	--exclude="Library/Preferences/Thoth Preferences" \
	--exclude="Library/Saved Searches" \
	--exclude="Library/Widgets" \
	--exclude="Microsoft User Data" \
	--exclude="Movies" \
	--exclude="Music" \
	--exclude="Pictures" \
	--exclude="Pics2WorkOn/*.psd" \
	--exclude="Pics2WorkOn/**/*.psd" \
	--exclude="Podcasts" \
	--exclude="Records/private/Video" \
	--exclude="Roxio Converted Items" \
	--exclude="Scanner Output" \
	--exclude="Sites" \
	--exclude="Temp" \
	--exclude="TV Shows" \
	--exclude="googleearth/kml/surfaces" \
	--exclude="*NOT_BACKED_UP*" \
	--exclude="github_repo/jakewendt/my_core/tmp/" \
	--exclude="github_repo/jakewendt/my_core/downloads/" \
	--exclude="github_repo/jakewendt/my_core/test/tmp/" \
	--exclude="github_repo/jakewendt/my_core/test/downloads/" \
	--exclude="hosting_rails" \
	--exclude="hostingrails.svn/**/attic/" \
	--exclude="hostingrails.svn/references/videos/" \
	--exclude="hostingrails.svn/sites/attic/my/log/" \
	--exclude="hostingrails.svn/sites/attic/my/tmp/" \
	--exclude="hostingrails.svn/sites/attic/my/downloads/" \
	--exclude="hostingrails.svn/sites/attic/my/test/downloads/" \
	--exclude="hostingrails.svn/sites/attic/my/test/tmp/" \
	--exclude="hostingrails.svn/sites/my/log/" \
	--exclude="hostingrails.svn/sites/my/tmp/" \
	--exclude="hostingrails.svn/sites/my/downloads/" \
	--exclude="hostingrails.svn/sites/my/test/downloads/" \
	--exclude="hostingrails.svn/sites/my/test/tmp/" \
	--exclude="hostingrails.svn/sites/netflix/query.log*" \
	--exclude="hostingrails.svn/sites/netflix/catalog" \
	--exclude="hostingrails.svn/sites/netflix/queries_*" \
	--exclude="hostingrails.svn/sites/netflix/DB*.sql" \
	--exclude="hostingrails.svn/sites/netflix/catalog*.sql" \
	--exclude="hostingrails.svn/sites/raider/query.log" \
	--exclude="hostingrails.svn/sites/raider/DB*.sql" \
	--exclude="hostingrails.svn/sites/www/ZNP?" \
	--exclude="hostingrails.svn/sites/www/LVPanorama" \
	--exclude="hostingrails.svn/sites/www/VRGPanorama" \
	--exclude="hostingrails.svn/sites/www/Speed" \
	--exclude="hostingrails.svn/sites/www/lamps" \
	--exclude="hostingrails.svn/sites/www/img" \
	--exclude="vendor/rails" \
	--exclude="rsync-backup" \
	--exclude="upillar.svn/" \
	--exclude="upillar.svn/motors/data_scripts/" \
	--exclude="upillar.svn/motors/vendor/" \
	--exclude="upillar.svn/motors/public/video/" \
	--exclude="upillar.svn/classifieds/trunk/lib/data/" \
	--exclude="upillar.svn/classifieds/trunk/vendor/" \
	--exclude="rsync/private/Video" \
	--exclude="log/*.log" \
	--exclude="versions" \
	--exclude=".android" \
	--exclude=".fseventsd" \
	--exclude=".rvm" \
	--exclude=".svn" \
	--exclude=".TemporaryItems" \
	--exclude=".Trash" \
	--exclude=".Trashes" \
	--exclude=".Spotlight-V100" \
	--exclude=".dvdcss" \
	--exclude=".jpi_cache" \
	--exclude=".DS_Store" \
	--exclude="Records" \
	--exclude="Documents" \
	--exclude="DroidX.sparsebundle" \
	--exclude="Recipe.sparsebundle" \
	--exclude="droid_x*" \
	/Users/jake/ $BackupDir/

#	--exclude="*sparsebundle" \

#/usr/bin/rsync -avz \
#	--progress \
#	--delete \
#	--extended-attributes \
#	--exclude="Scanner Output" \
#	--exclude="*NOT_BACKED_UP*" \
#	--exclude="log/*.log" \
#	/Users/jake/Documents/ $BackupDir/Documents/

touch $BackupDir/`date "+%y%m%d:%H%M%S"`
