#!/bin/sh -x

Date=`date "+%y%m%d%H%M%S"`

BackupDir=/Volumes/Passport/Backups/MBP

if [ ! -d $BackupDir ]
then
	echo "$BackupDir doesn't exist"
	exit
else
	echo "$BackupDir exists"
fi

#	-a = -rlptgoD
#	g - groups have become a problem so I'm ignorin em
#	t - times have become a problem so I'm ignorin em
#	D - devices are pointless here so I'm ignorin em
#	r - recursive
#	l - links
#	p - permissions
#	t - 
#	o - owner
#	v - verbose
#	z - compression
#	c - checksum
/usr/bin/rsync -rltpvz \
	--progress \
	--extended-attributes \
	--delete --backup --backup-dir rsync-backup-$Date \
	--exclude="AppleWorks User Data" \
	--exclude="Acrobat User Data" \
	--exclude="Android" \
	--exclude="Desktop/Incomplete" \
	--exclude="Downloads/*.mp4" \
	--exclude="Downloads/**/*.mp4" \
	--exclude="Eclipse" \
	--exclude="Library/Preferences/Macromedia" \
	--exclude="Library/Application Support/Garmin/Maps/*.gmap" \
	--exclude="Library/Application Support/SyncServices" \
	--exclude="Library/Caches" \
	--exclude="Library/Google" \
	--exclude="Library/Mail/Bundles (Disabled)/GPGMail.mailbundle" \
	--exclude="Library/Logs" \
	--exclude="Podcasts" \
	--exclude="Roxio Converted Items" \
	--exclude="Microsoft User Data" \
	--exclude="Temp" \
	--exclude="hosting_rails/prod/sites/www/*.m4v" \
	--exclude="TV Shows" \
	--exclude="rsync-backup*" \
	--exclude="log/*.log" \
	--exclude=.DS_Store \
	--exclude=.fseventsd \
	--exclude=.rvm \
	--exclude=.Trash \
	--exclude=.Trashes \
	--exclude=.TemporaryItems \
	--exclude=.Spotlight-V100 \
	--exclude=.dvdcss \
	--exclude=.jpi_cache \
	--exclude=\*NOT_BACKED_UP\* \
	/Users/jake/ $BackupDir/jake/


/usr/bin/rsync -rltpvz --progress \
	--delete --backup --backup-dir rsync-backup-$Date \
	--exclude=rsync-backup\* \
	--exclude=.DS_Store \
	--exclude=temp \
	--exclude=Viewed \
	--exclude=Incomplete \
	--exclude=Xtorrent \
	--exclude=\*NOT_BACKED_UP\* \
	--exclude="Downloads/*.mp4" \
	--exclude="Downloads/**/*.mp4" \
	--exclude="Downloads/**/*.wmv" \
	/Users/Shared/ $BackupDir/Shared/

