#!/bin/sh

rsync -avz \
	--exclude="20100606-Kickball.zip" \
	--exclude=".lastlogin" \
	--exclude=".cpan" \
	--exclude=".cpanel" \
	--exclude=".cpcpan" \
	--exclude="etc" \
	--exclude=".gem" \
	--exclude="mail" \
	--exclude=".MirrorSearch" \
	--exclude="prod/sites/googleearth" \
	--exclude="svn_old_server" \
	--exclude=".trash" \
	--exclude="prod/sites/*/log/*.log" \
	--exclude="prod/sites/my_tmp" \
	--exclude="prod/sites/my.090712" \
	--progress \
	jakewen@jakewendt.com: ~/hosting_rails/
